#Instead of using TAB for indentation, use two spaces at the place of one TAB

#Controller to control robot arm joints
robot_arm_controller:
  type: "position_controllers/JointTrajectoryController"
  joints: [Joint_1, Joint_2, Joint_3, Joint_4, Joint_5, Joint_6, Joint_7, Joint_8, Joint_9, Joint_10, Joint_11, Joint_12]

#Controller to continuously publish joint states/positions
joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50