# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - DERECHO_controller

  DERECHO_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - Joint_1
      - Joint_2
      - Joint_5
      - Joint_6
      - Joint_7
      - Joint_8