# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    DERECHO_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

DERECHO_controller:
  ros__parameters:
    joints:
      - Joint_1
      - Joint_2
      - Joint_5
      - Joint_6
      - Joint_7
      - Joint_8
    command_interfaces:
      - position
      - velocity
      - effort
    state_interfaces:
      - position
      - velocity
      - effort